media: ""
content:
  - name: shuoshuo
    label: 说说
    type: file
    path: shuoshuo/data.json
    format: json
    list: true
    fields:
      - name: date
        type: date
        required: true
        label: 时间
        options:
          time: true
      - name: content
        type: text
        label: 内容
        list: true
      - name: images
        type: image
        label: 图片
        list: true
      - name: pinned
        type: boolean
        label: 置顶
        default: false

  - name: oneword
    label: 一言
    type: file
    path: oneword.json
    format: json
    list: true
    fields:
      - name: sentence
        type: text
        required: true
        label: 句子

  - name: friends-json
    label: 友链(JSON)
    type: file
    path: friend.json

  - name: friends-yaml
    label: 友链(YAML)
    type: file
    path: friends.yaml
